In [7]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import seaborn as sns
import matplotlib.pyplot as plt
import re

In [54]:
dataframe = pd.read_csv("../enron_test_data.csv")

In [55]:
dataframe.head(5)

,Unnamed: 0,file,message
0,0,allen-p/_sent_mail/1.,Message-ID: <18782981.1075855378110.JavaMail.e...
1,1,allen-p/_sent_mail/10.,Message-ID: <15464986.1075855378456.JavaMail.e...
2,2,allen-p/_sent_mail/100.,Message-ID: <24216240.1075855687451.JavaMail.e...
3,3,allen-p/_sent_mail/1000.,Message-ID: <13505866.1075863688222.JavaMail.e...
4,4,allen-p/_sent_mail/1001.,Message-ID: <30922949.1075863688243.JavaMail.e...

In [56]:
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  5000 non-null   int64
 1   file        5000 non-null   object
 2   message     5000 non-null   object
dtypes: int64(1), object(2)
memory usage: 117.3+ KB

In [57]:
print(dataframe.message[6])

Message-ID: <16254169.1075863688286.JavaMail.evans@thyme>
Date: Tue, 22 Aug 2000 07:44:00 -0700 (PDT)
From: phillip.allen@enron.com
To: david.l.johnson@enron.com, john.shafer@enron.com
Subject:
Mime-Version: 1.0
Content-Type: text/plain; charset=us-ascii
Content-Transfer-Encoding: 7bit
X-From: Phillip K Allen
X-To: david.l.johnson@enron.com, John Shafer
X-cc:
X-bcc:
X-Folder: \Phillip_Allen_Dec2000\Notes Folders\'sent mail
X-Origin: Allen-P
X-FileName: pallen.nsf

Please cc the following distribution list with updates:

Phillip Allen (pallen@enron.com)
Mike Grigsby (mike.grigsby@enron.com)
Keith Holst (kholst@enron.com)
Monique Sanchez
Frank Ermis
John Lavorato


Thank you for your help

Phillip Allen

#### Looks like all these messages share the same structure, which is quite convenient. It means I can split the text by newline ('\n\') and then simply slice the resulting list to access specific elements of each email. Then I can assign them to new dataframe columns and clean them up for further exploration.

In [58]:
dataframe['text'] = dataframe['message'].apply(lambda message: message.split('\n')[15:])

In [59]:
dataframe.head(5)

,Unnamed: 0,file,message,text
0,0,allen-p/_sent_mail/1.,Message-ID: <18782981.1075855378110.JavaMail.e...,"[, Here is our forecast, , ]"
1,1,allen-p/_sent_mail/10.,Message-ID: <15464986.1075855378456.JavaMail.e...,"[, Traveling to have a business meeting takes ..."
2,2,allen-p/_sent_mail/100.,Message-ID: <24216240.1075855687451.JavaMail.e...,"[, test successful. way to go!!!]"
3,3,allen-p/_sent_mail/1000.,Message-ID: <13505866.1075863688222.JavaMail.e...,"[, Randy,, , Can you send me a schedule of th..."
4,4,allen-p/_sent_mail/1001.,Message-ID: <30922949.1075863688243.JavaMail.e...,"[, Let's shoot for Tuesday at 11:45. ]"

In [60]:
dataframe['date'] = dataframe['message'].apply(lambda message: message.split('\n')[1][6:])
dataframe['sender'] = dataframe['message'].apply(lambda message: message.split('\n')[2][6:])
dataframe['recipients'] = dataframe['message'].apply(lambda message: message.split('\n')[3][3:].split(','))
dataframe['subject'] = dataframe['message'].apply(lambda message: message.split('\n')[4][8:])

In [61]:
dataframe.head(7)

,Unnamed: 0,file,message,text,date,sender,recipients,subject
0,0,allen-p/_sent_mail/1.,Message-ID: <18782981.1075855378110.JavaMail.e...,"[, Here is our forecast, , ]","Mon, 14 May 2001 16:39:00 -0700 (PDT)",phillip.allen@enron.com,[ tim.belden@enron.com],
1,1,allen-p/_sent_mail/10.,Message-ID: <15464986.1075855378456.JavaMail.e...,"[, Traveling to have a business meeting takes ...","Fri, 4 May 2001 13:51:00 -0700 (PDT)",phillip.allen@enron.com,[ john.lavorato@enron.com],Re:
2,2,allen-p/_sent_mail/100.,Message-ID: <24216240.1075855687451.JavaMail.e...,"[, test successful. way to go!!!]","Wed, 18 Oct 2000 03:00:00 -0700 (PDT)",phillip.allen@enron.com,[ leah.arsdall@enron.com],Re: test
3,3,allen-p/_sent_mail/1000.,Message-ID: <13505866.1075863688222.JavaMail.e...,"[, Randy,, , Can you send me a schedule of th...","Mon, 23 Oct 2000 06:13:00 -0700 (PDT)",phillip.allen@enron.com,[ randall.gay@enron.com],
4,4,allen-p/_sent_mail/1001.,Message-ID: <30922949.1075863688243.JavaMail.e...,"[, Let's shoot for Tuesday at 11:45. ]","Thu, 31 Aug 2000 05:07:00 -0700 (PDT)",phillip.allen@enron.com,[ greg.piper@enron.com],Re: Hello
5,5,allen-p/_sent_mail/1002.,Message-ID: <30965995.1075863688265.JavaMail.e...,"[, Greg,, , How about either next Tuesday or ...","Thu, 31 Aug 2000 04:17:00 -0700 (PDT)",phillip.allen@enron.com,[ greg.piper@enron.com],Re: Hello
6,6,allen-p/_sent_mail/1003.,Message-ID: <16254169.1075863688286.JavaMail.e...,"[, Please cc the following distribution list w...","Tue, 22 Aug 2000 07:44:00 -0700 (PDT)",phillip.allen@enron.com,"[ david.l.johnson@enron.com, john.shafer@enro...",

In [63]:
pd.to_datetime(dataframe.date)

0       2001-05-14 16:39:00-07:00
1       2001-05-04 13:51:00-07:00
2       2000-10-18 03:00:00-07:00
3       2000-10-23 06:13:00-07:00
4       2000-08-31 05:07:00-07:00
                  ...
4995    2001-10-09 14:50:14-07:00
4996    2001-10-09 10:46:00-07:00
4997    2001-10-09 07:23:43-07:00
4998    2001-10-09 05:01:58-07:00
4999    2001-10-08 20:39:13-07:00
Name: date, Length: 5000, dtype: object

In [51]:
dataframe.head(5)

,Unnamed: 0,file,message,text,date,sender,recipients,subject
0,0,allen-p/_sent_mail/1.,Message-ID: <18782981.1075855378110.JavaMail.e...,"[, Here is our forecast, , ]",2001-05-14 16:39:00-07:00,phillip.allen@enron.com,[ tim.belden@enron.com],
1,1,allen-p/_sent_mail/10.,Message-ID: <15464986.1075855378456.JavaMail.e...,"[, Traveling to have a business meeting takes ...",2001-05-04 13:51:00-07:00,phillip.allen@enron.com,[ john.lavorato@enron.com],Re:
2,2,allen-p/_sent_mail/100.,Message-ID: <24216240.1075855687451.JavaMail.e...,"[, test successful. way to go!!!]",2000-10-18 03:00:00-07:00,phillip.allen@enron.com,[ leah.arsdall@enron.com],Re: test
3,3,allen-p/_sent_mail/1000.,Message-ID: <13505866.1075863688222.JavaMail.e...,"[, Randy,, , Can you send me a schedule of th...",2000-10-23 06:13:00-07:00,phillip.allen@enron.com,[ randall.gay@enron.com],
4,4,allen-p/_sent_mail/1001.,Message-ID: <30922949.1075863688243.JavaMail.e...,"[, Let's shoot for Tuesday at 11:45. ]",2000-08-31 05:07:00-07:00,phillip.allen@enron.com,[ greg.piper@enron.com],Re: Hello